### PR TITLE
add TLSRPT dashbboard

### PR DESCRIPTION
**Pull request by andreasbrett**
Introduces a rather simple TLSRPT dashboard. My experience with Kibana dashboard exports is rather limited. Haven't had a chance to test re-importing my dashboard yet.

### CODE REVIEW

**Comment by alexanderzeh** [comment]
Hey Andreas,
thanks for your work.
I wanted to test your dashboard.
After the import it shows up, but is empty. I guess there's simply no data in Kibana.
I definitely have received TLS reports. Do I need to add something else than "save_smtp_sts = True" in the [general] section of my parsedmarc.ini to work?
I can see in the log, that parsedmarc identified the TLS reports as such, processed and moved them to the Archive. It seems the data is just not stored in Kibana.

**Comment by andreasbrett** [comment]
Do you see the `smtp_tls-YYYY-MM` indices in your Elastic/Kibana instance?

**Comment by alexanderzeh** [comment]
nothing at all with smtp_tls*
That's what made me thinking nothing is added to Kibana by parsedmarc

**Comment by andreasbrett** [comment]
Did you reimport the Kibana ndjson after updating parsedmarc to a version with tlsrpt support?

**Comment by alexanderzeh** [comment]
I just recently installed parsedmarc, so it is the latest version 8.12.0 (I followed these steps: https://domainaware.github.io/parsedmarc/index.html)

I imported the ndjson from this PR afterwards (overwriting conflicts during import). Apparently that worked, as the new dashboard is there.

Running parsedmarc manually with a TLS report placed in the inbox with debug set to True shows me that parsedmarc recognizes the TLS report.

` DEBUG:__init__.py:1445:Processing message 26 of 26: UID 2710`
` INFO:__init__.py:1085:Parsing mail from tlsrpt-noreply@example.com on 2024-08-14 00:06:01-04:00`
` DEBUG:__init__.py:1545:Moving SMTP TLS report messages from INBOX to Archive/SMTP-TLS`
` DEBUG:__init__.py:1553:Moving message 1 of 1: UID 2710`

**Comment by alexanderzeh** [comment]
I found the issue.

**Comment by sdnr** [comment]
Hi,
I got an {"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred."} when I tried to import these dashboard to kibana 7.17.24
The previous version works without errors

**Pull request merged**
