### PR TITLE
Implemented Azure Log Analytics ingestion via Data Collection Rules

### PR DESCRIPTION
**Pull request by rubeste**

### CODE REVIEW

**Comment by seanthegeek** [comment]
Please fix the issues identified by flake8 **https://github.com/domainaware/parsedmarc/actions/runs/4498555538/jobs/8088590875?pr=394**

**Comment by seanthegeek** [comment]
Also, add any new dependencies to pyproject.toml

**Comment by rubeste** [comment]
I fixed the styling errors and added `azure-monitor-ingestion` to the pyproject.toml

**Comment by seanthegeek** [comment]
Two more small style fixes are needed (add a space after your if keywords) https://github.com/domainaware/parsedmarc/actions/runs/4607585069/jobs/8698597478?pr=394

**Comment by seanthegeek** [comment]
Weird. Now there are PEP8 errors in files that you didn't even modify. I'll fix those myself.

**Pull request merged**
